// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCCPG9pRe4kiSDZdSk-xLmAMwCsM0Z7EY',
    appId: '1:991871048466:web:b58a706e33b8f78d0bf1cb',
    messagingSenderId: '991871048466',
    projectId: 'app-fatec-lista-tarefas-c97e0',
    authDomain: 'app-fatec-lista-tarefas-c97e0.firebaseapp.com',
    storageBucket: 'app-fatec-lista-tarefas-c97e0.appspot.com',
    measurementId: 'G-M5VZTZCKB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP8bGIipIs3nzqcTH-ycMZn1OF98ef7jA',
    appId: '1:991871048466:android:bde4094127e94a9d0bf1cb',
    messagingSenderId: '991871048466',
    projectId: 'app-fatec-lista-tarefas-c97e0',
    storageBucket: 'app-fatec-lista-tarefas-c97e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUO8yDYHcFHt47D-9fHsW5dYdV6fm-Ky0',
    appId: '1:991871048466:ios:7eb472fa1255ce800bf1cb',
    messagingSenderId: '991871048466',
    projectId: 'app-fatec-lista-tarefas-c97e0',
    storageBucket: 'app-fatec-lista-tarefas-c97e0.appspot.com',
    iosBundleId: 'com.example.motoMotoFirebase',
  );
}
